### ISSUE TITLE
Graph API returns Unsupported get requests.

### ISSUE THREAD

**Issue by chonla** [aiaio/galleria-facebook#12]
Facebook Graph API returns the following JSON when retrieving album.

/**/ jQuery111205592851671390235_1427392673346({
   "error": {
      "message": "Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
      "type": "GraphMethodException",
      "code": 100
   }
});

**Comment by apumapho** [comment]
Any more info to share on what is causing this error?  What is the id of your album?  Can you provide code samples or a link to the page loading the gallery?

From: chonla
Reply-To: aiaio/galleria-facebook
Date: Thursday, March 26, 2015 at 2:53 PM
To: aiaio/galleria-facebook
Subject: [galleria-facebook] Graph API returns Unsupported get requests. (#12)


Facebook Graph API returns the following JSON when retrieving album.

/**/ jQuery111205592851671390235_1427392673346({
"error": {
"message": "Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
"type": "GraphMethodException",
"code": 100
}
});

**Comment by chonla** [comment]
Album id: 797249163691728
Album link: https://www.facebook.com/lumpoo.b/media_set?set=a.797249163691728.1073742084.100002199540144&type=1

Here's the embedded code.
<script src="/assets/global/plugins/galleria/galleria-1.4.2.min.js"></script>
<script src="/assets/global/plugins/galleria/plugins/facebook/galleria.facebook.js"></script>
<script type="text/javascript">
Galleria.loadTheme('/assets/global/plugins/galleria/themes/classic/galleria.classic.min.js');
Galleria.run('#galleria', {
 facebook: 'album:797249163691728',
 width: 745,
 height: 550,
 lightbox: true});
</script>

**Comment by apumapho** [comment]
Prior update to Facebook API version resolved issue
