### ISSUE TITLE
target _blank

### ISSUE THREAD

**Issue by emessix** [aiaio/galleria-facebook#15]
Hi everybody,

I have activated the backlink to facebook on the pictures but i would like choose the target _blank to open a new window. But i can't find the solution with the new version of galleria-facebook.

Please can you help me?

**Comment by apumapho** [comment]
@emessix Try the [popupLinks](http://galleria.io/docs/options/popupLinks/) option:

popupLinks
type: Boolean
default: false

Setting this to true will open any image links in a new window. You can add image links using the longdesc attribute (default) or customize it using data_config
