### ISSUE TITLE
Unable to retrieve Facebook photos from album

### ISSUE THREAD

**Issue by zacpowjt** [aiaio/galleria-facebook#17]
I got this:

![screen shot 2015-08-27 at 6 16 16 am](https://cloud.githubusercontent.com/assets/13937046/9507808/2bb03c04-4c83-11e5-9abc-569924d4ce50.png)

I generated the token as advised on https://smashballoon.com/custom-facebook-feed/access-token/ but that token doesn't work. Even though i lived the app, it still returns me the same results.

The facebook group's photo album is public: https://www.facebook.com/media/set/?set=oa.1796690780557524&type=1

I placed my App token, in the url below for testing and it doesn't work, returns me nothing.
https://graph.facebook.com/1796690780557524/photos?access_token=[TOKEN}

This is what I got:
{
   "data": [

   ]
}

Am I getting the wrong token ? Please help.

**Comment by osj2507** [comment]
I have the same problem and it is also mentioned by @suprememind in [issue 14](https://github.com/aiaio/galleria-facebook/issues/14) I can use my own token and show the example album 303027476429477 (from http://www.gagacenter.com/nyc/gaga-photos/Kid%20Gaga/2/) but I cannot show my own album, the album is public, you should be able to see it via this link
https://www.facebook.com/media/set/?set=a.1072704456669.2011693.1197870145&type=1&l=5dc392c0ed

I do however get a list of items return, if I use the call with my token
https://graph.facebook.com/1796690780557524/photos?access_token=[TOKEN]

So what am I doing wrong? Why can't I access my own albums?

**Comment by apumapho** [comment]
@osj2507 what album ID are you trying with?  What is the full URL being called by the plugin?  (you can see this in Chrome's dev tools > network tab, or similar)  What happens if you open an incognito/private browser and hit that url?

**Comment by osj2507** [comment]
@apumapho According to the guide I am using the first part after the a. in the link

https://www.facebook.com/media/set/?set=a.1072704456669.2011693.1197870145&type=1&l=5dc392c0ed

That should be 1072704456669 as far as I can see

**Comment by madesignUK** [comment]
Did you ever get this resolved - as 1 year on funnily I am getting the exact same problem.

hope you are still connected to github

**Comment by osj2507** [comment]
I did not get this resolved no and ended up not using the plugin, we went with another solution all together.

**Comment by madesignUK** [comment]
When someone CLOSES a Thread

Could they please put a clear MESSAGE - WHY?

**Comment by madesignUK** [comment]
osj2507  - out of interest what did you go with - currently evaluating 2 different so called FB gallery importers, but both have a similar issue.

**Comment by zacpowjt** [comment]
WHY - No further development is being done on this plugin.

**Comment by madesignUK** [comment]
So please SAY so, rather than just CLOSING a forum.

So DOES THIS PLUGIN NOT WORK then?

Can you CLEARLY PLEASE CONFIRM THIS

**Comment by osj2507** [comment]
madesignUK - We ended up just making a gallery and hosted the images on a server/site instead of getting them through facebook.

**Comment by madesignUK** [comment]
Thanks – may have found a solution for us both

Clive
