### ISSUE TITLE
Empty Output to Website

### ISSUE THREAD

**Issue by chriscather** [aiaio/galleria-facebook#18]
I'm working with a website using Galleria and there is absolutely no output to the website. Not a gallery, not an error, nothing. Before I updated the scripts it was pulling in the images, but now nothing. I've tried manually retrieving the data using this method (https://graph.facebook.com/ALBUM_ID/photos?access_token=ACCESS_TOKEN) and I get good results.

Any suggestions?

**Comment by apumapho** [comment]
Hi Chris — share some code, your album_id, and public access token, and we might be able to take a look and help you out.

**Comment by apumapho** [comment]
CLOSED (pending code, access token, or album_id to verify with...)
