### ISSUE TITLE
Using Facebook Api

### ISSUE THREAD

**Issue by madesignUK** [aiaio/galleria-facebook#19]
OK, just spent the day getting this not to work.
I have downloaded all the updates, including re-edited the facebook.js file to the 2015 updated version, that's not in the facebook plugin download.

I've mirrored coding from 
      http://www.gagacenter.com/nyc/gaga-photos/Tour%20the%20New%20York%20Facility/1/

to ensure that all works, using someone elses coding/ and Facebook api access (thank you)

But as soon as I switch to my own album: and facebook_access_token.... well I get
Unable to retrieve X Facebook photos from album 10154274827845896

(I added the X in the error message)

I created a fully local working version using Kids Gaga web page to make sure it wasn't a local issue - This all works fine.

But cannot get Facebook Token to work, and cannot get images to load.
Noticed that Facebook api is now version 2.8, and the facebook plugin is 2.3
Here is the working and none working version of the basic script...

http://clientswebsite.co.uk/assets/galleria/themes/classic/classic-demo-Facebook-TST.php

hope you can confirm its a FACEBOOK token issue?

and a work around for this
With thanks in advance

Clive

**Comment by apumapho** [comment]
@madesignUK It does appear to be a Facebook token problem.  The plugin and the Facebook API are working.  Did you go [through the steps to create the API token](https://github.com/aiaio/galleria-facebook/issues/14)?

**Comment by madesignUK** [comment]
Thanks for the feed forward

 

Is it a plugin ONLY for Facebook PAGE with a photo album.

 

Or does it work with the Main Profile page Photo Albums?

 

I was working with Main Profile Photo Albums

 

With thanks in advance

**Comment by apumapho** [comment]
@madesignUK Correct, this only works with public albums, not your profile pictures album and not with any private albums.

**Comment by akula9703** [comment]
For me problem is not solve. I have 'Unable to retrieve ...'. I red #14 and still same. Can anyone help me?

**Comment by apumapho** [comment]
@akula9703 - can you share a link to your album and provide the token you generated?

**Comment by akula9703** [comment]
The problem was a misplaced space between album and value.
