### ISSUE TITLE
100 limit

### ISSUE THREAD

**Issue by bubble33** [aiaio/galleria-facebook#21]
Hi
There seems to be a limited of how many facebook images get pulled in to 100. Can I increase this limit?

Thanks

**Comment by apumapho** [comment]
@bubble33 Facebook API limits to 100, though this value does seem to change up and down over time.  You could experiment with trying higher values with newer versions of the API which may return more photo records.

Practically, however, you'd likely not want to load more than 100 photos into the gallery in one shot.  Facebook designs the limits to take into consideration many factors of JSON payload size, the photos themselves, etc, to download.

If you really want to get past the 100 photo limit, you could also look into paging through the full results and appending additional sets of 100 photos to the array that Galleria loads into its control.
