### ISSUE TITLE
Using this plug-in with Folio Theme

### ISSUE THREAD

**Issue by archetypestudio** [aiaio/galleria-facebook#7]
I'm running into a problem with using the Folio theme. Since the theme is responsive I wanted to remove the Width/Height options. I get an error when I remove those. Can you make this responsive?

**Comment by apumapho** [comment]
The latest version of galleria (1.4.2) and the facebook plugin (on git) supports a fully responsive site.  I've found the best results setting one of height or width when you instantiate the gallery, but it could also work without setting either depending on how your containing CSS is setup.  Responsive layout is on by default in the latest galleria.
