### ISSUE TITLE
Paging Graph API changed

### ISSUE THREAD

**Issue by rodekker** [aiaio/galleria-facebook#9]
The paging was changed in the graph-syntax. Please change galleria.facebook.js.

Change: 

var url = 'http://graph.facebook.com/' + params['album_id'] + '?callback=?' + '&fields=photos.fields(images,source,picture,link,name)&photos.limit=' + this.options.max;

into: 

var url = 'http://graph.facebook.com/' + params['album_id'] + '?callback=?' + '&fields=photos.limit('+this.options.max+').fields(images,source,picture,link,name)';

**Comment by apumapho** [comment]
Fixed in the latest release using v2.3 Graph API syntax.
